//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Book {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Book() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryManager.Resources.Book", typeof(Book).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new book.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed.
        /// </summary>
        public static string Borrowed {
            get {
                return ResourceManager.GetString("Borrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to borrowed.
        /// </summary>
        public static string Borrowed_Info_1 {
            get {
                return ResourceManager.GetString("Borrowed_Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string Borrowed_Info_2 {
            get {
                return ResourceManager.GetString("Borrowed_Info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since.
        /// </summary>
        public static string Borrowed_Info_3 {
            get {
                return ResourceManager.GetString("Borrowed_Info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and should be returned by.
        /// </summary>
        public static string Borrowed_Info_4 {
            get {
                return ResourceManager.GetString("Borrowed_Info_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string Delete_Confirm_1 {
            get {
                return ResourceManager.GetString("Delete_Confirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book with id.
        /// </summary>
        public static string Delete_Confirm_2 {
            get {
                return ResourceManager.GetString("Delete_Confirm_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string Delete_Confirm_3 {
            get {
                return ResourceManager.GetString("Delete_Confirm_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and its all borrows?.
        /// </summary>
        public static string Delete_Confirm_4 {
            get {
                return ResourceManager.GetString("Delete_Confirm_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book deleting.
        /// </summary>
        public static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book is currently.
        /// </summary>
        public static string Is_Borrowed_Info {
            get {
                return ResourceManager.GetString("Is_Borrowed_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books list.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage authors.
        /// </summary>
        public static string Manage_Authors {
            get {
                return ResourceManager.GetString("Manage_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication year.
        /// </summary>
        public static string Publication_Year {
            get {
                return ResourceManager.GetString("Publication_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unborrowed.
        /// </summary>
        public static string Unborrowed {
            get {
                return ResourceManager.GetString("Unborrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unborrowed.
        /// </summary>
        public static string Unborrowed_Info {
            get {
                return ResourceManager.GetString("Unborrowed_Info", resourceCulture);
            }
        }
    }
}
